### PR TITLE
feat: add interactive config generator

### LINKED ISSUE #1106: Interactive config generator
`dipdup new` command currently can render one of templates with minor variations. Let's call it "from template" mode. We also need an "interactive mode". Start from empty config, then ask repetitive questions to construct config. Possible steps:

- Add contract -> Select kind -> Set address/hash -> Repeat?
- Add datasource -> Select kind -> Set URL/keys -> Repeat?
- Add index -> Select kind -> Select contracts/events  ->Repeat?

When done, dump resulting YAML as a root config. There's a tricky thing in this task, compose-style env variables.

### PR DESCRIPTION
**Pull request by JoE11-y**
for #1106 

completed

To test:
- run dipdup new
- select network
- select build from scratch

@droserasprout

### CODE REVIEW

**Review by droserasprout — CHANGES_REQUESTED** [review]
Hi! Thanks for the contribution. Adventure mode looks and works really great! Some suggestions for the current implementation:

1. There is no option to spawn a completely empty project without choosing a blockchain (`demo_blank` itself). Maybe we should add it to the list of templates. Or better make the first question "Template / Interactively / Blank"?
2. Datasources loop should start with "Add datasource? [Y/n]". The only required fields in config are package and spec_version, everything else can be spawned later
3. Yes-no questions code should be reused. Something like `dipdup.install.ask`. 
4. "Neutral" datasources (without blockchain prefix in kind) should be presented in this menu.
5. Make sure to run `make all docs` before push (even if it fails at the moment)

**Comment by JoE11-y** [comment]
I adjusted the interaction flow as requested. Now:

1. Datasources and contracts are independent of each other and can be set selectively.
2. However Indexers require datasources (mandatory) and may also depend on contracts, depending on the indexer type, for the configuration to pass the final validation check.

All possible scenarios were carefully considered in the update.

**Comment by JoE11-y** [comment]
> Hi! Thanks for the contribution. Adventure mode looks and works really great! Some suggestions for the current implementation:
> 
>     1. There is no option to spawn a completely empty project without choosing a blockchain (`demo_blank` itself). Maybe we should add it to the list of templates. Or better make the first question "Template / Interactively / Blank"?
> 
>     2. Datasources loop should start with "Add datasource? [Y/n]". The only required fields in config are package and spec_version, everything else can be spawned later
> 
>     3. Yes-no questions code should be reused. Something like `dipdup.install.ask`.
> 
>     4. "Neutral" datasources (without blockchain prefix in kind) should be presented in this menu.
> 
>     5. Make sure to run `make all docs` before push (even if it fails at the moment)

completed

**Review by droserasprout — APPROVED** [review]
Solid work, thank you!

**Pull request merged**
